"""empty message

Revision ID: 3d1dc4acccfa
Revises: None
Create Date: 2016-08-22 14:39:20.414499

"""

# revision identifiers, used by Alembic.
revision = '3d1dc4acccfa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
